#!/usr/bin/env bash
# tmux-claude-status installer.
# Copies the hook script into ~/.claude/, registers Claude Code hooks in
# ~/.claude/settings.json, and sources a generated tmux config fragment.
# Idempotent: safe to re-run for upgrades.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
CLAUDE_DIR="$HOME/.claude"
SCRIPT_DEST="$CLAUDE_DIR/tmux-status.sh"
CONF_DEST="$CLAUDE_DIR/tmux-claude-status.conf"
SETTINGS="$CLAUDE_DIR/settings.json"
MARKER_BEGIN='# >>> tmux-claude-status >>>'
DEFAULT_BORDER_FORMAT='#{?pane_active,#[reverse],}#{pane_index}#[default] "#{pane_title}"'
# Styles use #[fg=x]#[bg=y] (not #[fg=x,bg=y]) — a comma inside the badge would
# terminate the surrounding #{?,,} conditional.
BADGE='#{?#{==:#{@claude_status},working},#[fg=black]#[bg=yellow] ⇄ working #[default] ,#{?#{==:#{@claude_status},blocked},#[fg=white]#[bg=red] ✻ blocked #[default] ,#{?#{==:#{@claude_status},idle},#[fg=black]#[bg=green] · idle #[default] ,}}}'

die() { echo "error: $*" >&2; exit 1; }

command -v python3 >/dev/null || die "python3 is required to edit settings.json safely"
[ -d "$CLAUDE_DIR" ] || die "$CLAUDE_DIR not found; install and run Claude Code first"
command -v tmux >/dev/null || echo "warning: tmux not found on PATH; installing anyway (the hook no-ops outside tmux)" >&2

# 1. Hook script.
install -m 0755 "$REPO_DIR/tmux-status.sh" "$SCRIPT_DEST"
echo "installed $SCRIPT_DEST"

# 2. Capture the pre-install pane-border-format so the badge composes with it.
#    On re-install, reuse the value stored by the previous install — capturing
#    live again would nest our own badge into itself.
orig=""
if [ -f "$CONF_DEST" ]; then
  orig="$(sed -n "s/^set -g @claude_border_orig '\(.*\)'$/\1/p" "$CONF_DEST" | head -n1)"
  [ -n "$orig" ] && echo "reusing original border format captured by previous install"
fi
if [ -z "$orig" ] && command -v tmux >/dev/null && tmux ls >/dev/null 2>&1; then
  orig="$(tmux show -gv pane-border-format 2>/dev/null || true)"
  case "$orig" in *@claude_status*) orig="" ;; esac
fi
case "$orig" in
  *"'"*)
    echo "warning: existing pane-border-format contains a single quote; falling back to the tmux default format" >&2
    orig=""
    ;;
esac
[ -n "$orig" ] || orig="$DEFAULT_BORDER_FORMAT"

# 3. Generate the tmux config fragment.
{
  printf '# Generated by tmux-claude-status install.sh\n'
  printf '# Edit badge text/colours below. @claude_border_orig preserves your pre-install\n'
  printf '# pane-border-format; do not hand-edit that line.\n'
  printf "set -g @claude_status_badge '%s'\n" "$BADGE"
  printf "set -g @claude_border_orig '%s'\n" "$orig"
  printf 'set -g pane-border-status top\n'
  printf "set -g pane-border-format '#{E:@claude_status_badge}#{E:@claude_border_orig}'\n"
} > "$CONF_DEST"
echo "generated $CONF_DEST"

# 4. Source the fragment from the user's tmux conf (append-only: preserves symlinks).
if [ -e "$HOME/.tmux.conf" ]; then
  TMUX_CONF="$HOME/.tmux.conf"
elif [ -e "$HOME/.config/tmux/tmux.conf" ]; then
  TMUX_CONF="$HOME/.config/tmux/tmux.conf"
else
  TMUX_CONF="$HOME/.tmux.conf"
  : > "$TMUX_CONF"
fi
if grep -qF "$MARKER_BEGIN" "$TMUX_CONF"; then
  echo "$TMUX_CONF already sources tmux-claude-status"
else
  if [ -s "$TMUX_CONF" ] && [ "$(tail -c1 "$TMUX_CONF")" != "" ]; then
    printf '\n' >> "$TMUX_CONF"
  fi
  printf '\n%s\nsource-file %s\n%s\n' "$MARKER_BEGIN" "$CONF_DEST" '# <<< tmux-claude-status <<<' >> "$TMUX_CONF"
  echo "added source block to $TMUX_CONF"
fi

# 5. Register hooks in Claude Code global settings (atomic, backup, idempotent).
python3 - "$SETTINGS" <<'PY'
import json, os, shutil, sys

path = sys.argv[1]
settings = {}
if os.path.exists(path):
    with open(path) as f:
        raw = f.read()
    if raw.strip():
        try:
            settings = json.loads(raw)
        except ValueError as e:
            sys.exit(f"error: {path} is not valid JSON ({e}); fix it and re-run (file left untouched)")
    shutil.copy2(path, path + ".tmux-claude-status.bak")

MARK = "tmux-status.sh"
hooks = settings.get("hooks") or {}

def strip_ours(groups):
    kept_groups = []
    for group in groups:
        entries = group.get("hooks")
        if isinstance(entries, list):
            kept = [h for h in entries if MARK not in str(h.get("command", ""))]
            if not kept:
                continue
            group = {**group, "hooks": kept}
        kept_groups.append(group)
    return kept_groups

for event in list(hooks):
    groups = strip_ours(hooks[event])
    if groups:
        hooks[event] = groups
    elif hooks[event]:
        del hooks[event]

CMD = "~/.claude/tmux-status.sh"
for event, matcher, state in [
    ("UserPromptSubmit", None, "working"),
    ("PostToolUse", None, "working"),
    ("PreToolUse", "AskUserQuestion", "blocked"),
    ("Notification", "permission_prompt", "blocked"),
    ("Stop", None, "idle"),
    ("SessionEnd", None, "clear"),
]:
    group = {"hooks": [{"type": "command", "command": f"{CMD} {state}"}]}
    if matcher:
        group = {"matcher": matcher, **group}
    hooks.setdefault(event, []).append(group)

settings["hooks"] = hooks
tmp = path + ".tmp"
with open(tmp, "w") as f:
    json.dump(settings, f, indent=2)
    f.write("\n")
os.replace(tmp, path)
print(f"registered hooks in {path} (backup: {path}.tmux-claude-status.bak)")
PY

# 6. Apply live if a tmux server is running.
if command -v tmux >/dev/null && tmux ls >/dev/null 2>&1; then
  tmux source-file "$CONF_DEST"
  echo "applied to the running tmux server"
fi

echo
echo "done. Claude Code reloads settings automatically, so running sessions pick this up too."
echo "try it:   $SCRIPT_DEST blocked     (then: $SCRIPT_DEST clear)"
